// Services

export const CYCLING_POWER_SERVICE = 0x1818
export const DEVICE_INFORMATION_SERVICE = 0x180a

// Characteres

export const MODEL_NUMBER_CHARACTERISTIC = 0x2A24
export const SERIAL_NUMBER_CHARACTERISTIC = 0x2A25
export const FIRMWARE_REVISION_CHARACTERISTIC = 0x2A26
export const HARDWARE_REVISION_CHARACTERISTIC = 0x2A27
export const SOFTWARE_CHARACTERISTIC = 0x2A28
export const MANUFACTURER_NAME_CHARACTERISTIC = 0x2A29


// CPS
export const SENSOR_LOCATION_CHARACTERISTIC = 0x2A5D
export const CYCLING_POWER_MEASUREMENT_CHARACTERISTIC = 0x2A63
export const CYCLING_POWER_FEATURE_CHARACTERISTIC = 0x2A65



// Descriptors

export const CHARACTERISTIC_USER_DECRIPTION_DESCRIPTOR = 0x2901